/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{html,ts}",
    ],
    safelist: [
        // DaisyUI button classes
        'btn',
        'btn-primary',
        'btn-secondary',
        'btn-accent',
        'btn-ghost',
        'btn-outline',
        'btn-error',
        'btn-sm',
        'btn-md',
        'btn-lg',
        'btn-circle',
        // DaisyUI badge classes
        'badge',
        'badge-primary',
        'badge-secondary',
        'badge-accent',
        'badge-ghost',
        'badge-outline',
        'badge-info',
        'badge-success',
        'badge-warning',
        'badge-error',
        'badge-neutral',
        'badge-sm',
        'badge-md',
        'badge-lg',
        // DaisyUI alert classes
        'alert',
        'alert-info',
        'alert-success',
        'alert-warning',
        'alert-error',
        // DaisyUI toast classes
        'toast',
        'toast-top',
        'toast-bottom',
        'toast-start',
        'toast-end',
    ],
    theme: {
        extend: {
            colors: {
                'olive-green': '#6B7F4C',
                'sage-green': '#8B9A6C',
                'warm-cream': '#FFF8F0',
                'light-beige': '#F5E6D3',
                'medium-beige': '#E8D5BC',
            },
            fontFamily: {
                'heading': ['Playfair Display', 'serif'],
                'body': ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
            }
        },
    },
    daisyui: {
        themes: [
            {
                pastahaus: {
                    "primary": "#6B7F4C",
                    "primary-content": "#ffffff",
                    "secondary": "#E8D5BC",
                    "secondary-content": "#3D3D3D",
                    "accent": "#8B9A6C",
                    "accent-content": "#ffffff",
                    "neutral": "#3D3D3D",
                    "neutral-content": "#ffffff",
                    "base-100": "#FFF8F0",
                    "base-200": "#F5E6D3",
                    "base-300": "#E8D5BC",
                    "base-content": "#3D3D3D",
                    "info": "#3ABFF8",
                    "info-content": "#ffffff",
                    "success": "#36D399",
                    "success-content": "#ffffff",
                    "warning": "#FBBD23",
                    "warning-content": "#3D3D3D",
                    "error": "#F87272",
                    "error-content": "#ffffff",
                },
            },
        ],
        darkTheme: false,
        base: true,
        styled: true,
        utils: true,
    },
    plugins: [require("daisyui")],
}